In [83]:
import os, sys
import pandas as pd
import plotly.graph_objects as go
import io

In [84]:
path = os.getcwd()
dirs = os.listdir( path +'/Data/RTE')
dirs.sort()
i = 0
for file in dirs:
    df = pd.read_csv('Data/RTE/'+file,encoding="ISO-8859-1", sep='\t', low_memory=False, index_col=0, header = [0,1])
    df= df.replace("*", 0)

In [103]:
type('2.5') is str

True

In [113]:
'2,5'.replace(',', ';')

'2;5'

In [114]:
def change_col_to_point(x):
    if type(x) is str:
        x = x.replace(',', '.')
        return float(x)
    else:
        return float(x)

In [116]:
df = df.applymap(change_col_to_point)

In [122]:
df.groupby(level=0, axis=1).sum()

,Autre,Biomasse,Charbon,Fioul,Gaz,Hydraulique STEP,Hydraulique fil de l'eau / éclusée,Hydraulique lacs,Nucléaire,Unnamed: 148_level_0,Éolien en mer
01/01/2023 00:00-01:00,1.0,120.0,-1.0,1.0,605.0,-877.5,0.0,539.5,25897.0,0.0,0.0
01/01/2023 01:00-02:00,1.0,120.0,-1.0,0.5,604.0,-1176.0,0.0,639.0,25736.0,0.0,0.0
01/01/2023 02:00-03:00,1.0,120.0,-1.0,-0.5,603.5,-1014.0,44.0,187.5,25171.5,0.0,0.0
01/01/2023 03:00-04:00,1.0,120.0,-1.0,-0.5,666.5,-1120.5,0.0,59.0,24613.5,0.0,0.0
01/01/2023 04:00-05:00,1.0,120.0,-1.0,-1.0,611.5,-2312.0,0.0,0.0,24532.5,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
24/04/2023 20:00-21:00,0.0,155.5,0.0,1.0,4020.0,1224.5,156.5,606.0,35682.5,0.0,140.0
24/04/2023 21:00-22:00,0.0,154.0,0.0,0.5,4017.5,1227.0,151.5,670.5,35902.5,0.0,124.0
24/04/2023 22:00-23:00,0.0,135.5,-0.5,1.0,3710.5,930.5,75.5,732.5,35943.5,0.0,130.0
24/04/2023 23:00-24:00,0.0,130.0,-0.5,0.5,3562.5,543.0,70.5,624.5,35964.0,0.0,117.0
25/04/2023 00:00-01:00,0.0,130.0,-1.0,0.5,3560.0,537.5,71.5,370.5,35783.0,0.0,117.0